// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "cca2ca23-c255-43d4-bf48-3d7cacc5e41f");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1653473119);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1653577317);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{988d6b9c-8d45-497c-849c-892e281b433f}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1653473112);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 122);
user_pref("browser.newtabpage.activity-stream.impressionId", "{84824994-2886-4b69-a0dd-a11feb597f7d}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1653473116);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1653577319455");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1653598919455");
user_pref("browser.search.region", "MY");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20220202182137");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1653577317");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20220202182137");
user_pref("browser.startup.homepage_override.mstone", "97.0");
user_pref("browser.startup.homepage_override.once", "{\"message_id\":\"WNP_MOMENTS_13\",\"url\":\"https://www.mozilla.org/firefox/welcome/13\",\"expire\":1640908800000}");
user_pref("browser.startup.lastColdStartupCheck", 1653577317);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1653473118405");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "97.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "MY");
user_pref("dom.push.userAgentID", "410bad956f414bae97cdf228eda7e4f4");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20220202182137");
user_pref("extensions.lastAppVersion", "97.0");
user_pref("extensions.lastPlatformVersion", "97.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"d751b750-e26a-4fdb-b8c1-2a92f3e48a99\",\"formautofill@mozilla.org\":\"e8fc9d1b-75ca-469a-bb01-fc04f3d851fd\",\"pictureinpicture@mozilla.org\":\"c5f56b36-6d05-4886-87ca-d6bdd5822d08\",\"screenshots@mozilla.org\":\"7885ed6d-7d37-4807-8fb7-463d0065f9ee\",\"webcompat-reporter@mozilla.org\":\"66450e34-b1d5-4924-a15d-8626a9ea597b\",\"webcompat@mozilla.org\":\"beae3647-151f-4d4e-bee4-01d345947e25\",\"default-theme@mozilla.org\":\"1573d867-8103-437d-9135-242a5e2ef62f\",\"addons-search-detection@mozilla.com\":\"e8c665ea-0007-4ed1-b570-929beed3312e\",\"google@search.mozilla.org\":\"bc44d541-00a0-46da-a708-2ea369d07d84\",\"amazondotcom@search.mozilla.org\":\"d751c769-55ca-4933-ab91-897759d554d7\",\"wikipedia@search.mozilla.org\":\"77140dff-f381-4f75-a4f3-3c9b96cec739\",\"bing@search.mozilla.org\":\"eccb6db5-44a6-4421-840e-6aa1c7a209f4\",\"ddg@search.mozilla.org\":\"39a1dbc7-56c8-422d-ba00-1303c72c52fa\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1653473119);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "86f50a48-cd4f-410a-97bd-d30e1cf7ea2e");
user_pref("toolkit.startup.last_success", 1653577314);
user_pref("toolkit.telemetry.cachedClientID", "771770cb-d845-4124-9441-b511c095f3c1");
user_pref("toolkit.telemetry.previousBuildID", "20220202182137");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
